import os
import tempfile
from pathlib import Path

import streamlit as st
from dotenv import load_dotenv

from services.ai_service import generate_script, generate_voiceover
from services.video_service import generate_video_from_script
from services.youtube_service import upload_to_youtube

load_dotenv()

st.set_page_config(page_title="YouTube Automation Studio", page_icon="🎬", layout="wide")


st.title("🎬 YouTube Automation Studio")
st.caption("Create scripts, voiceovers, and simple YouTube-ready videos in one flow.")

with st.sidebar:
    st.header("Settings")
    st.markdown("Use your API keys here or set them in a `.env` file.")
    st.session_state.openai_api_key = st.text_input(
        "OpenAI API Key", type="password", value=os.getenv("OPENAI_API_KEY", "")
    )
    st.session_state.elevenlabs_key = st.text_input(
        "ElevenLabs API Key", type="password", value=os.getenv("ELEVENLABS_API_KEY", "")
    )
    st.session_state.youtube_client_id = st.text_input(
        "YouTube Client ID", value=os.getenv("YOUTUBE_CLIENT_ID", "")
    )
    st.session_state.youtube_client_secret = st.text_input(
        "YouTube Client Secret", type="password", value=os.getenv("YOUTUBE_CLIENT_SECRET", "")
    )

    st.markdown("---")
    st.info(
        "This starter app creates an easy workflow for Shorts, facts videos, and documentary-style clips using AI text + voice + video scenes."
    )


with st.form("content_form"):
    topic = st.text_input("Video Topic", placeholder="Example: 5 little-known facts about black holes")
    tone = st.selectbox("Tone", ["Educational", "Casual", "Powerful", "Storytelling", "News-style"])
    style = st.selectbox("Video Style", ["Shorts", "News / Facts", "Documentary", "Sticky character style"])
    language = st.selectbox("Language", ["English", "Hindi", "Spanish", "French", "Arabic"])
    length = st.slider("Video Length (minutes)", min_value=0.5, max_value=8.0, value=2.0, step=0.5)
    voice = st.selectbox("Voice", ["female", "male", "neutral"])
    auto_upload = st.checkbox("Auto upload to YouTube if credentials are available", value=False)

    submitted = st.form_submit_button("Generate Video")

if submitted:
    if not topic:
        st.warning("Please enter a topic before generating a video.")
        st.stop()

    output_dir = Path("output")
    output_dir.mkdir(exist_ok=True)

    with st.spinner("Creating your script, voiceover, and video..."):
        script = generate_script(
            topic=topic,
            tone=tone,
            style=style,
            language=language,
            duration_minutes=length,
            api_key=st.session_state.openai_api_key,
        )

        st.subheader("AI Script")
        st.write(script)

        voice_path = generate_voiceover(
            text=script,
            output_path=str(output_dir / "voiceover.mp3"),
            language=language,
            voice=voice,
            elevenlabs_api_key=st.session_state.elevenlabs_key,
        )

        final_video = output_dir / "final_video.mp4"
        generate_video_from_script(
            script=script,
            audio_path=voice_path,
            output_path=str(final_video),
            style=style,
        )

        if auto_upload:
            upload_result = upload_to_youtube(
                video_path=str(final_video),
                title=f"{topic} | {style}",
                description=f"Generated by YouTube Automation Studio\n\nTopic: {topic}\nStyle: {style}\nTone: {tone}",
                client_id=st.session_state.youtube_client_id,
                client_secret=st.session_state.youtube_client_secret,
            )
            st.success(f"Video generated and upload status: {upload_result['status']}")
        else:
            st.success("Video generated successfully.")

        with open(final_video, "rb") as f:
            st.download_button(
                label="Download final video",
                data=f.read(),
                file_name="final_video.mp4",
                mime="video/mp4",
            )

        st.markdown("---")
        st.subheader("Project files")
        st.write({
            "Script": str(output_dir / "script.txt"),
            "Voiceover": voice_path,
            "Final video": str(final_video),
        })

else:
    st.info("Fill in the form and click 'Generate Video' to start.")

    st.markdown("### App Features")
    st.markdown(
        """
        - Script generation with OpenAI or offline fallback
        - Voiceover generation with ElevenLabs or gTTS
        - Video scene generation with captions and visual overlays
        - Quick export for Shorts, facts, or documentary-style videos
        - Optional YouTube upload using API credentials
        """
    )

    st.markdown("### Suggested content workflow")
    st.markdown(
        """
        1. Enter a topic.
        2. Choose your tone and style.
        3. Generate a video.
        4. Download or upload it to YouTube.
        """
    )
    
    st.markdown("### Example topics")
    st.code("Top 5 unknown facts about space\nWhy your brain creates shortcuts\nThe weird history of social media\n3 surprising inventions from the 1800s")


if __name__ == "__main__":
    pass
