import os
import re
from typing import List

import numpy as np
from PIL import Image, ImageDraw, ImageFont
from moviepy.editor import AudioFileClip, CompositeVideoClip, ImageClip, TextClip, concatenate_videoclips


def _split_script(script: str) -> List[str]:
    sections = [part.strip() for part in re.split(r"\n\s*\n+", script) if part.strip()]
    if not sections:
        return [script.strip()]
    return sections[:6]


def _wrap_text(draw, text: str, max_width: int, font, max_lines: int = 5) -> List[str]:
    words = text.split()
    lines = []
    current = ""

    for word in words:
        candidate = f"{current} {word}".strip()
        if draw.textbbox((0, 0), candidate, font=font)[2] <= max_width:
            current = candidate
        else:
            if current:
                lines.append(current)
            current = word
            if len(lines) >= max_lines - 1:
                break
    if current:
        lines.append(current)
    return lines


def _make_scene_image(title: str, body: str, accent: tuple) -> Image.Image:
    width, height = 1280, 720
    image = Image.new("RGB", (width, height), (14, 18, 28))
    draw = ImageDraw.Draw(image)

    try:
        font_big = ImageFont.truetype("DejaVuSans-Bold.ttf", 52)
        font_small = ImageFont.truetype("DejaVuSans.ttf", 32)
    except Exception:
        font_big = ImageFont.load_default()
        font_small = ImageFont.load_default()

    # Add subtle gradient-like effect
    for y in range(height):
        ratio = y / height
        r = int(20 + (255 - 20) * ratio)
        g = int(25 + (120 - 25) * ratio)
        b = int(40 + (180 - 40) * ratio)
        draw.line([(0, y), (width, y)], fill=(r, g, b))

    # Top-left accent bar
    draw.rectangle((80, 90, 220, 135), fill=accent)
    draw.text((250, 90), "YOUTUBE AI", fill=(255, 255, 255), font=font_small)

    # Title
    title_lines = _wrap_text(draw, title[:80], 900, font_big, max_lines=2)
    y = 180
    for line in title_lines[:2]:
        draw.text((80, y), line, fill=(255, 255, 255), font=font_big)
        y += 60

    # Body text
    body_lines = _wrap_text(draw, body, 1100, font_small, max_lines=6)
    y = 380
    for line in body_lines[:6]:
        draw.text((80, y), line, fill=(220, 230, 255), font=font_small)
        y += 42

    # Bottom caption patch
    draw.rounded_rectangle((80, 620, 1200, 685), radius=18, fill=(10, 12, 26, 200))
    draw.text((105, 635), "Generated by YouTube Automation Studio", fill=(255, 255, 255), font=font_small)
    return image


def generate_video_from_script(script: str, audio_path: str, output_path: str, style: str = "Shorts") -> str:
    os.makedirs(os.path.dirname(output_path) or ".", exist_ok=True)
    sections = _split_script(script)

    clips = []
    seconds_per_section = 4 if style.lower() == "shorts" else 5

    for index, section in enumerate(sections):
        title = f"Scene {index + 1}"
        body = section
        accent = (20, 184, 166) if index % 2 == 0 else (255, 155, 50)
        image = _make_scene_image(title, body, accent)
        frame = np.array(image)

        clip = ImageClip(frame, duration=seconds_per_section).resize((1280, 720))
        clips.append(clip)

    if not clips:
        raise ValueError("No scenes were created from the provided script.")

    final_clip = concatenate_videoclips(clips, method="compose")

    if os.path.exists(audio_path):
        audio = AudioFileClip(audio_path)
        final_clip = final_clip.set_audio(audio)
    else:
        raise FileNotFoundError(f"Audio file not found: {audio_path}")

    final_clip.write_videofile(
        output_path,
        fps=24,
        codec="libx264",
        audio_codec="aac",
        temp_audiofile=os.path.join(os.path.dirname(output_path), "tmp_audio.wav"),
        remove_temp=True,
    )
    return output_path
