import os
import re
from typing import List

import numpy as np
from PIL import Image, ImageDraw, ImageFont
from moviepy.editor import AudioFileClip, CompositeAudioClip, ImageClip, TextClip, concatenate_videoclips


def _split_script(script: str) -> List[str]:
    cleaned = script.replace("\r", "").strip()
    if not cleaned:
        return ["Scene 1"]

    blocks = re.split(r"\n\s*\n+", cleaned)
    sections = []
    for block in blocks:
        stripped = block.strip()
        if stripped:
            sections.append(stripped)

    if not sections:
        return [cleaned]

    final_sections = []
    for section in sections:
        paragraphs = re.split(r"(?<=[.!?])\s+", section)
        for p in paragraphs:
            p = p.strip()
            if p and len(p) > 25:
                final_sections.append(p)
    return final_sections[:8]


def _wrap_text(draw, text: str, max_width: int, font, max_lines: int = 5) -> List[str]:
    words = text.split()
    lines = []
    current = ""

    for word in words:
        candidate = f"{current} {word}".strip()
        if draw.textbbox((0, 0), candidate, font=font)[2] <= max_width:
            current = candidate
        else:
            if current:
                lines.append(current)
            current = word
            if len(lines) >= max_lines - 1:
                break
    if current:
        lines.append(current)
    return lines if lines else [text[:40]]


def _make_scene_image(title: str, body: str, accent: tuple) -> Image.Image:
    width, height = 1280, 720
    image = Image.new("RGB", (width, height), (12, 18, 30))
    draw = ImageDraw.Draw(image)

    try:
        font_big = ImageFont.truetype("DejaVuSans-Bold.ttf", 52)
        font_small = ImageFont.truetype("DejaVuSans.ttf", 28)
    except Exception:
        font_big = ImageFont.load_default()
        font_small = ImageFont.load_default()

    for y in range(height):
        ratio = y / height
        r = int(12 + (25 - 12) * ratio)
        g = int(20 + (45 - 20) * ratio)
        b = int(38 + (90 - 38) * ratio)
        draw.line([(0, y), (width, y)], fill=(r, g, b))

    draw.rounded_rectangle((85, 80, 260, 130), radius=18, fill=accent)
    draw.text((110, 92), "AI VIDEO", fill=(255, 255, 255), font=font_small)

    title_lines = _wrap_text(draw, title[:80], 860, font_big, max_lines=2)
    y = 170
    for line in title_lines[:2]:
        draw.text((90, y), line, fill=(255, 255, 255), font=font_big)
        y += 58

    body_lines = _wrap_text(draw, body, 1060, font_small, max_lines=6)
    y = 320
    for line in body_lines[:6]:
        draw.text((90, y), line, fill=(220, 230, 255), font=font_small)
        y += 36

    draw.rounded_rectangle((80, 620, 1200, 680), radius=18, fill=(8, 12, 20, 200))
    draw.text((100, 636), "Generated by YouTube Automation Studio", fill=(255, 255, 255), font=font_small)
    return image


def _make_caption_overlay(text: str, duration: float) -> TextClip:
    return (
        TextClip(
            text=text,
            fontsize=38,
            color="white",
            font="DejaVuSans-Bold.ttf",
            method="caption",
            size=(1200, 120),
            stroke_color="black",
            stroke_width=3,
        )
        .set_position((40, 600))
        .set_duration(duration)
    )


def _write_srt(subtitle_path: str, sections: List[str], base_duration: float) -> None:
    if not subtitle_path:
        return
    os.makedirs(os.path.dirname(subtitle_path) or ".", exist_ok=True)

    rows = []
    total_time = 0.0
    for idx, segment in enumerate(sections, start=1):
        start = total_time
        end = total_time + max(base_duration, min(7, len(segment.split()) * 0.22))
        start_fmt = _format_srt_time(start)
        end_fmt = _format_srt_time(end)
        rows.append(f"{idx}\n{start_fmt} --> {end_fmt}\n{segment[:120]}\n")
        total_time = end

    with open(subtitle_path, "w", encoding="utf-8") as f:
        f.write("\n".join(rows))


def _format_srt_time(seconds: float) -> str:
    hours = int(seconds // 3600)
    minutes = int((seconds % 3600) // 60)
    secs = int(seconds % 60)
    millis = int(round((seconds - int(seconds)) * 1000))
    return f"{hours:02d}:{minutes:02d}:{secs:02d},{millis:03d}"


def generate_video_from_script(
    script: str,
    audio_path: str,
    output_path: str,
    style: str = "Shorts",
    captions: bool = True,
    subtitle_path: str | None = None,
    music_path: str | None = None,
    music_volume: float = 0.12,
) -> str:
    os.makedirs(os.path.dirname(output_path) or ".", exist_ok=True)
    sections = _split_script(script)

    if subtitle_path:
        _write_srt(subtitle_path, sections, 4 if style.lower() == "shorts" else 5)

    clips = []
    base_section_duration = 4 if style.lower() == "shorts" else 5

    for index, section in enumerate(sections):
        title = f"Scene {index + 1}"
        body = section
        accent = (20, 184, 166) if index % 2 == 0 else (255, 155, 50)
        image = _make_scene_image(title, body, accent)
        frame = np.array(image)

        clip_duration = max(base_section_duration, min(7, len(section.split()) * 0.22))
        clip = ImageClip(frame, duration=clip_duration).resize((1280, 720))

        if captions:
            caption_clip = _make_caption_overlay(body[:60], clip_duration)
            clip = concatenate_videoclips([clip, caption_clip], method="compose")

        clips.append(clip)

    if not clips:
        raise ValueError("No scenes were created from the provided script.")

    final_clip = concatenate_videoclips(clips, method="compose")

    if os.path.exists(audio_path):
        voice_audio = AudioFileClip(audio_path)
        final_clip = final_clip.set_audio(voice_audio)
        if music_path and os.path.exists(music_path):
            music_audio = AudioFileClip(music_path).volumex(music_volume)
            combined = CompositeAudioClip([
                voice_audio.volumex(1.0),
                music_audio.set_start(0),
            ])
            final_clip = final_clip.set_audio(combined)
            final_clip = final_clip.subclip(0, min(final_clip.duration, max(voice_audio.duration, music_audio.duration)))
        else:
            final_clip = final_clip.subclip(0, min(final_clip.duration, voice_audio.duration))
    else:
        raise FileNotFoundError(f"Audio file not found: {audio_path}")

    final_clip.write_videofile(
        output_path,
        fps=24,
        codec="libx264",
        audio_codec="aac",
        temp_audiofile=os.path.join(os.path.dirname(output_path), "tmp_audio.wav"),
        remove_temp=True,
    )
    return output_path
